---
- name: Install packages needed to use the Kubernetes apt repository
  apt:
    update_cache: true
    name:
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gpg
  become: true

- name: Check if the kubernetes signing key file exists
  stat:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  register: k8s_gpg_key_check

- name: Download the public signing key for the Kubernetes package repositories
  shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: not k8s_gpg_key_check.stat.exists

- name: Add repository for kubernetes 1.28 to Apt sources
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    state: present
    create: yes
  become: true
  register: out_add_repository

- name: Install packages needed to use the Kubernetes apt repository
  apt:
    update_cache: true
    name:
      - kubelet 
      - kubeadm 
      - kubectl
  become: true

- name: Prevent kubernetes being upgraded
  shell: apt-mark hold kubelet kubeadm kubectl
  become: true