---
- name: Check if Docker is installed
  command: "docker --version"
  ignore_errors: true
  register: docker_check

- name: Install Docker and containerd
  block:
  - name: apt-get update
    apt:
      update_cache: true
      name: 
        - ca-certificates 
        - curl 
        - gnupg

  - name: Create directory /etc/apt/keyrings
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Check if the Docker GPG key file exists
    stat:
      path: /etc/apt/keyrings/docker.asc
    register: docker_gpg_key_check

  - name: Fetch the Docker GPG key and save the dearmored key
    shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.asc
    when: not docker_gpg_key_check.stat.exists

  - name: Change the permmision of dearmored key
    ansible.builtin.file:
      path: /etc/apt/keyrings/docker.asc
      mode: a+r

  - name: Get version codename
    shell: . /etc/os-release && echo $VERSION_CODENAME
    register: os_version_codename

  - name: Get arch
    shell: dpkg --print-architecture
    register: os_arch
    changed_when: false

  - name: Print codename and arch
    debug:
      msg: "Codename: {{ os_version_codename.stdout }}, arch: {{ os_arch.stdout }}"

  - name: Add repository to Apt sources
    ansible.builtin.lineinfile:
      path: /etc/apt/sources.list.d/docker.list
      line: "deb [arch={{ os_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ os_version_codename.stdout }} stable"
      state: present
      create: yes
    register: out_add_repository

  - name: Test add repository
    debug:
      msg: "{{ out_add_repository }}"

  - name: Run apt-get update and install docker packages
    apt:
      update_cache: true
      name:
        - docker-ce
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin
  become: true
  when: docker_check.rc != 0

- name: Comment out disabled_plugins in /etc/containerd/config.toml
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml 
    search_string: disabled_plugins = ["cri"]
    line: "# disabled_plugins = [\"cri\"]"
    state: present
  become: true

- name: Set /etc/containerd/config.toml
  ansible.builtin.blockinfile:
    path: /etc/containerd/config.toml 
    block: |
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
          SystemdCgroup = true
  become: true
  register: config_changed

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
  become: true
  when: config_changed is changed